name: Generate Datas

on:
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Snake Animation
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: BiancaTacola
          svg_out_path: dist/github-contribution-grid-snake.svg

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
  
  - nome: Cache
  usa: ações/cache@v1.2.1
  com:
    # Um diretório para armazenar e salvar o cache
    caminho:
    # Uma chave explícita para restaurar e salvar o cache
    chave:
    # Uma lista ordenada de chaves a serem usadas para restaurar o cache se nenhuma ocorrência de cache ocorreu para a chave
    chaves de restauração: # opcional
